### ISSUE TITLE
Исходники по отдельным репозитриям

### ISSUE THREAD

**Issue by andreystarkov** [tsvetkovpro/sources#1]
Почему бы не распределить твои исходники по 1 репозиторию на каждый элемент. В едином сложно следить за твоими проектами и тем более -- принимать в них участие.

**Comment by tsvetkovpro** [comment]
Ты прав, видимо надо сделать так, можно подробнее. что означает по 1 на каждый элемент? сколько в итоге репозиториев нужно будет сделать?

**Comment by andreystarkov** [comment]
Ну, у тебя же сейчас все твои наработки в 1 большом репозитории, за которым сложно следить и тем более принимать участие в разработке. Было бы правильно на каждый проект или наработку создавать новый репозиторий.

**Comment by tsvetkovpro** [comment]
ок. так и надо сделать. мне кажется просто не найдёшь ничего потом если будет 100500 реп. Как думаешь?

**Comment by andreystarkov** [comment]
думаю, что 100500 узкоспециализированных реп это круто. к примеру, мне понравился твой скрипт -- я его форкнул и тут уже назревает пулл реквест. а у тебя получается, что всё в куче. сложно ориентироваться. да и потенциальные работодатели тоже оценят количество твоих тематических репозиториев. да и вообще это правильно, что ли)

**Comment by andreystarkov** [comment]
у тебя там ещё и исходники проектов в .zip-ах. да ты знаешь толк в извращениях!

**Comment by tsvetkovpro** [comment]
хотел сделать как удобнее)) ты прав. нарежу отдельные репы.

**Comment by tsvetkovpro** [comment]
выполнил.

**Comment by andreystarkov** [comment]
круто же! красавчик
